FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10-stretch-run
RUN apt update && apt install python build-essential libasound2-dev ntpdate alsa-utils -qy
WORKDIR /usr/src/app
COPY package.json package.json
RUN npm install
COPY . ./
ENV UDEV=1
CMD ["npm", "start"]
