version: '2'
services:
  server:
    build: '.'
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
    devices:
      - "/dev/snd:/dev/snd/"
      - "/dev/bus/usb:/dev/bus/usb"
    cap_add:
      - NET_ADMIN
    environment:
      - UDEV=1
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
